# Generated by Django 4.1.1 on 2022-10-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='name',
            new_name='item_category',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='description',
        ),
        migrations.AddField(
            model_name='inventory',
            name='branch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_model',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='p_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='p_out',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad')], default='Good', max_length=20),
        ),
        migrations.AddField(
            model_name='inventory',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_image'),
        ),
    ]
