# Generated by Django 4.1.1 on 2022-10-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_name_inventory_item_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IT_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('item_category', models.CharField(max_length=255)),
                ('item_description', models.CharField(max_length=255)),
                ('item_model', models.CharField(max_length=255)),
                ('p_in', models.IntegerField(blank=True, null=True)),
                ('p_out', models.IntegerField(blank=True, null=True)),
                ('branch', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad')], default='Good', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory_image')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='inventory',
            new_name='Design_Inventory',
        ),
    ]
