# Generated by Django 4.1.1 on 2022-10-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_design_inventory_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_inventory',
            name='status',
            field=models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad'), ('blank', 'blank')], default='Good', max_length=20),
        ),
        migrations.AlterField(
            model_name='it_inventory',
            name='status',
            field=models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad'), ('blank', 'blank')], default='Good', max_length=20),
        ),
    ]
